version: '3.9'
services:
  blog-database:
    image: mongo
    ports:
      - '27017:27017'
  blog-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://localhost:27017/recipe-sharing
    ports:
      - '3001:3001'
    depends_on:
      - blog-database
  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: https://effective-space-winner-57xq45x7w9xhprv4-3001.app.github.dev/api/v1
    ports:
      - '3000:80'
    depends_on:
      - blog-backend